uint8 INIT = 0                                       # 初始化状态  
uint8 SEARCHING_PARKING_SPACE = 1                    # 搜寻停靠点
uint8 NAVIGATE_TO_POSE = 21                          # navigate_to_pose 
uint8 WELT = 2                                       # 贴边停靠
uint8 GENERATE_PATH = 3                              # 生成路径
uint8 NAVIGATE_THROUGH_POSES = 22                    # navigate_through_poses
uint8 WAITING = 99                                   # 等待车辆通过
uint8 state